name: Maven Snapshots, Pull Requests, and Tagging

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Validate Maven wrapper
        run: |
          ./mvnw --version
          echo "M2_HOME=${JAVA_HOME}" >> $GITHUB_ENV

      - name: Build and Test with Maven
        run: ./mvnw clean install

      - name: Deploy snapshots and tag release on main branch
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        run: |
          VERSION=$(./mvnw -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
          if [[ $VERSION == *"-SNAPSHOT" ]]; then
            ./mvnw deploy
          else
            git config user.name "GitHub Actions"
            git config user.email "github-actions@users.noreply.github.com"
            git tag "v$VERSION" || echo "Tag v$VERSION already exists."
            git push origin --tags
          fi
